### ISSUE TITLE
add percent coverage as tooltip for Function Network Visualization 

### ISSUE THREAD

**Issue by bburns632** [uptake/pkgnet#110]
In the Function Network visualization, it would be nice to see the percent coverage for a function in the hover over. 

It would most likely be an edit/addition to [plot_network](https://github.com/UptakeOpenSource/pkgnet/blob/master/R/AbstractGraphReporter.R#L312) function. 

~See~ [~this `vizNetwork` example~](https://datastorm-open.github.io/visNetwork/interaction.html) See [this page instead](https://datastorm-open.github.io/visNetwork/nodes.html)

**Comment by darshandoshi95** [comment]
I am working on it.

**Comment by darshandoshi95** [comment]
I believe by percentage here it means as class core?

**Comment by jayqi** [comment]
This is a better documentation page for implementing tooltips: https://datastorm-open.github.io/visNetwork/nodes.html

I will edit the top comment.

**Comment by bburns632** [comment]
Hi @darshandoshi95, 

We are moving ahead with a v0.4.0 release without the feature.  This idea is being staged for the next release (v.0.5.0) temporarily. However, the theme, goal and scope of v.0.5.0 is open for discussion in #208, and I encourage you to join the conversation.
