### ISSUE TITLE
A "Get Started" Page?

### ISSUE THREAD

**Issue by bburns632** [uptake/pkgnet#156]
As it turns out, if you have an article with the same name as the package (e.g., vignettes/pkgdown.Rmd for pkgdown), it will automatically appear in the navigation bar under “Get Started”.  ([doc link](https://pkgdown.r-lib.org/articles/pkgdown.html#navigation-bar)). 

Do we want a "Get Started" section on the nav bar?

Does the readme suffice for a "get started" page?   

Do we need another vignette or just relocate/rename the existing one? 

Thoughts appreciated.

**Comment by jameslamb** [comment]
oh interesting. I'm comfortable with the current vignette being a "Get Started"
