### ISSUE TITLE
Add version information to dependency structure

### ISSUE THREAD

**Issue by jameslamb** [uptake/pkgnet#178]
In R, it is possible to add version floors by specifying something like this in a package's `DESCRIPTION` file:

```
Imports:
    data.table (>= 0.10.0)
```

This information should be added in the labels on nodes in `DependencyReporter`, so that instead of seeing that a package depends on `some_pkg`, you can see that it depends on `some_pkg (>= some_version)`.

**Comment by zwycl** [comment]
Hello, I would like to work on this for Hacktoberfest!

**Comment by bburns632** [comment]
@zwycl That would be much appreciated!  Thank you.  Please reach out with any questions.

**Comment by zwycl** [comment]
Two observations:

1. I can't find a `package_dependencies` function variant that would also extract version information. So it seems that I will need to manually extract the versions doing something like `deps <- unlist(strsplit(db[package,private$dep_types],",[[:space:]]*"))` and strsplit for the second half of the dependency information (the `(>= 0.10.0)` part)

2. We would also need propagate the version information throughout the `recursive_dependencies` recursive call for cases when two or more packages share the same dependency package but one package requires a higher version. We should compare and display the higher version on the dependency structure graph.

Please correct me if I am wrong, thanks!

**Comment by bburns632** [comment]
To be fair, `devtools::parse_deps()` is just doing string manipulation (pretty close to what you described above), but at least it is a stable and well maintained string parsing process.  If things changed in R, it would be updated quickly. 

![image](https://user-images.githubusercontent.com/24531403/66406750-c085fb00-e9b1-11e9-9b29-31ed956ed731.png)
