### ISSUE TITLE
pkgnet logo

### ISSUE THREAD

**Issue by bburns632** [uptake/pkgnet#185]
This package needs a logo.  Any ideas?

**Comment by bmb804** [comment]
How about a hexagonal network or web like [this](https://hexnet.org/files/images/hexnet/i-hexnum.png) or [this](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPSmF7sOF1cCQ-0X4VEu9H1ny0xU8kGlIQ1EWuNkO3wPuEUaMS) or [this](https://image.shutterstock.com/image-vector/cobweb-vector-icon-isolated-on-450w-1181173414.jpg). Or I was thinking you could do a play on basketball like [this](https://user-images.githubusercontent.com/7953022/54227316-a9d7fe00-44cd-11e9-9902-e0254c41af6c.png)
).

**Comment by jameslamb** [comment]
Of those, I kinda like the basketball one! Remember that we need space on the hex sticker for the package name. I like that that one has some empty space in the middle.
