### ISSUE TITLE
Recreate vignette on latest public versions of lubridate and pkgnet

### ISSUE THREAD

**Issue by bburns632** [uptake/pkgnet#196]
We need to recreate the vignette with specific versions of BOTH `lubridate` and `pkgnet` and update the "A Deeper Look" with instructions utilizing `devtools::install_version()` (or some other more R way to install specific versions) to replicate the analysis.  

This will prevent #189 from happening again in the future.  Considering that #181 is updating the content to align with itself, we can save this vignette update until after the next pushed version to github

**Comment by jayqi** [comment]
I actually disagree with pegging pkgnet version. I think in general, if we're making changes that we anticipate to affect the vignette static content, it's the responsibility of that PR contributor to update the vignette. Additionally, I think before we do a release, we should check the vignette. It makes more sense to me for our vignette to be up-to-date with the latest release of pkgnet.
