### ISSUE TITLE
feature idea: Dependency License Reporter

### ISSUE THREAD

**Issue by jameslamb** [uptake/pkgnet#199]
This is not a fully-formed idea, but leaving here to start a discussion. If `pkgnet` is supposed to help answer the question "should I add / remove this dependency?", I think it would be valuable to try to implement a `DependencyLicenseReporter` which lists the licenses of packages in your dependency tree.

Inspired by [`pip-licenses`](https://github.com/raimon49/pip-licenses).

**Comment by bburns632** [comment]
@jameslamb, what about, as a start, adding licenses as an additional column to the main data.table?

**Comment by jameslamb** [comment]
> @jameslamb, what about, as a start, adding licenses as an additional column to the main data.table?

That's a good idea, I'm cool with that. I won't be able to contribute it for a while though. Shall I make a separate issue from this one listing that as a proposed feature?

By the way that problem can get REALLY difficult really fast ([read this code](https://github.com/raimon49/pip-licenses/blob/master/piplicenses.py)) , to the extent that we should probably look into existing solutions or create our own outside of the `pkgnet` project.
