### ISSUE TITLE
Vignettes Capturing User Stories

### ISSUE THREAD

**Issue by bburns632** [uptake/pkgnet#219]
Hey all, 

I think it would be cool to have a user stories / testimonials section on the website.  Thoughts? 

If that sounds good, I think vignettes is the right place for it (would show up in articles section on website).  However, which is better: 

1. A section in the articles page of the website with one link per user story (i.e. one vignette per user story) or..
2. One article with multiple user stories (i.e. one vignette that we expand over time)

**Comment by jameslamb** [comment]
Love this idea!

I think one article with multiple user stories. Article title like `What problems can pkgnet solve?`

Then Table of Contents in that article like:

* `help you decide what do test (pkg name, user name)`
* `help you decide whether to factor out a dependency (pkg name, user name)`
* etc.
