### ISSUE TITLE
Columns whose values are integers should be printed w/o decimals

### ISSUE THREAD

**Issue by mattdzugan** [uptake/pkgnet#228]

**Comment by bburns632** [comment]
This is within the tables rendered at the bottom of the tabs in the report.

**Comment by j450h1** [comment]
I can take a crack at this one.

**Comment by bburns632** [comment]
Please do. That would be great.

**Comment by j450h1** [comment]
This should be complete as per latest PR. I tested out using the ggplot2 example in Readme and visually checked both tables which contain numeric values.

**Comment by j450h1** [comment]
I also noticed the current README has a gif/video that shows the old version with 3 decimal rounding for all numeric columns, so eventually, that will need to be updated as well. Maybe a good idea to keep this issue open until that is complete.
