### ISSUE TITLE
Strategy / Vision Documentation

### ISSUE THREAD

**Issue by bburns632** [uptake/pkgnet#230]
I think we have good docs on the high level scope ([README Introduction](https://github.com/UptakeOpenSource/pkgnet/blob/master/README.md)) and tactical "how to" for contributors ([CONTRIBUTING.md](https://github.com/UptakeOpenSource/pkgnet/blob/master/CONTRIBUTING.md)), but I think we are lacking in long term vision/strategy.  

This recent question from @cyberninja22 I think highlights the need: 
> @jameslamb @bburns632 does the implementation use only the base packages ? is it okay to use other packages , since I saw that libraries associated with this package are all base (mostly?) . let me know

https://github.com/UptakeOpenSource/pkgnet/issues/116#issuecomment-483055219

While @jameslamb's response is on point, this should be readily available information along with _why_ we strive to keep package dependencies low and _what_ might justify a new set of dependencies. 

To address this, I plan to:

1. create a `VISION.md` file to outline the long term vision/strategy, aligning with [github best practices](https://opensource.guide/best-practices/)
2. edit parts of the [README](https://github.com/UptakeOpenSource/pkgnet/blob/master/README.md) and [CONTRIBUTING.md](https://github.com/UptakeOpenSource/pkgnet/blob/master/CONTRIBUTING.md) to align.

**Comment by jameslamb** [comment]
TIL `VISION.md`, that sounds good to me.

I think it would be good to link Milestones to VISION.md, so people reading that file can click through to see particular ways they can contribute (issues) on a part of the vision that they care about.

**Comment by bburns632** [comment]
This package is being maintained but no significantly different revisions being planned on in the near future.  Closing version planning docs.
