### ISSUE TITLE
Add CODEOWNERS file

### ISSUE THREAD

**Issue by jameslamb** [uptake/pkgnet#232]
I learned about [this cool thing](https://help.github.com/en/articles/about-code-owners) from @Paxanator and @mjermann over in `fRanz`. GitHub allows you to add a `CODEOWNERS` file that will be used to set default reviewers when PRs are opened.

This has to be done by a repo admin, so assigning to you @bburns632 

We should do this so we automatically are added as reviewers when people submit PRs!

**Comment by jameslamb** [comment]
@bburns632 I went to contribute one of these today and realized we had this old issue that was closed.

Was it closed accidentally, or are you opposed to using a `CODEOWNERS` file?

Going to re-open so we can discuss

**Comment by bburns632** [comment]
We currently have a CODEOWNERS file.  Closed b/c it was added.

**Comment by jameslamb** [comment]
ohhhh ok I see it now. I'm used to it being in `.github/` so I overlooked it.

I think something about how we set it up is not working. No one got added as a code owner when I opened https://github.com/uptake/pkgnet/pull/278

**Comment by jayqi** [comment]
It looks like we had this problem: https://github.community/t5/How-to-use-Git-and-GitHub/CODEOWNERS-works-with-users-but-not-teams/td-p/4986

I just added our team with write permissions to uptake/pkgnet and uptake/pkgnet-gallery, so supposedly it should start working from now on.

**Comment by jameslamb** [comment]
Oh awesome, thanks Jay!
