### ISSUE TITLE
Base packages should be colored differently

### ISSUE THREAD

**Issue by austin3dickey** [uptake/pkgnet#238]
Hi folks -- long-time listener, first-time caller,

I think it would be useful if base packages (e.g. `grDevices`, `stats`, etc.) were highlighted differently in the graph. It would help me figure out at a glance which dependencies are unavoidable. I've sketched a possible vision in the attached picture.

[This R help post](http://r.789695.n4.nabble.com/List-of-default-packages-that-come-with-R-td4661857.html) details a possible way to find the names of all packages that come preinstalled with R.

Thanks!

![image (1)](https://user-images.githubusercontent.com/16600275/62057339-12a5e580-b1e5-11e9-8b9b-13a50919dec5.png)

**Comment by jameslamb** [comment]
Good idea! Created #239 too
