### ISSUE TITLE
Use GitHub teams?

### ISSUE THREAD

**Issue by jayqi** [uptake/pkgnet#241]
GitHub has a [teams](https://help.github.com/en/articles/changing-team-visibility) capability that we can create a handle for @ mentions. We can potentially make one for pkgnet for people more easily mention all of us in issues or in PRs.

**Comment by jayqi** [comment]
@uptake/pkgnet testing.

**Comment by jayqi** [comment]
I'm not sure if non-uptake-org people can use this handle or not, based on the description in GitHub's documentation. Will need to find someone to test.

**Comment by alistaire47** [comment]
@uptake/pkgnet testing more

**Comment by jayqi** [comment]
Alright, it looks like this doesn't work for people outside of the Uptake organization. Not that useful for public OSS repos.
