### ISSUE TITLE
feature: dropdown in report to choose between node coloring paradigms

### ISSUE THREAD

**Issue by bburns632** [uptake/pkgnet#247]
There are a few good ideas regarding useful colorings of nodes in the report.  It is hard to choose, but why do we?!

What if we had a why to put a dropdown button in the report?  This button would control how the nodes are colored.  The default could be #239 (one node) or maybe #238 (base R nodes).  However, via the drop down, one could change to #199 (by license), color by file type, author, the file they are within (#32) or whatever future fields we add.

**So, how could we put a dropdown button in the report that re-renders the vizNetwork when it changes?**

**Comment by dmi3kno** [comment]
I would like to see the table and the graph connected. Dropdown in the table would be nice, but maybe you could only allow unidirectional control from the graph (by selecting a node).
I think you need crosstalk.

**Comment by bburns632** [comment]
This package is not under active development.  We always welcome contributions, but there are no immediately plans for new features at the moment.  Consequently, closing this item.
