### ISSUE TITLE
Mac builds are broken on Travis

### ISSUE THREAD

**Issue by jameslamb** [uptake/pkgnet#250]
See, for example, https://travis-ci.org/uptake/pkgnet/jobs/596707485

Seems our Mac OS builds are failing because newer versions of `data.table` require libomp? Or at least try to use it by default?

I'm unsure (writing this issue somewhat hastily).

![image](https://user-images.githubusercontent.com/7608904/66673118-8e7ccf00-ec25-11e9-8696-4724379ae033.png)

It's possibly that this could be automagically fixed by adding a `brew install libomp` to our setup or by pegging to an older `data.table` version. If neither of those works, we can try using a different compiler that has it bundled, so something like:

```
brew install gcc
export CXX=/usr/local/bin/g++
export CC=/usr/local/bin/gcc
```

**Comment by jameslamb** [comment]
this issue is blocking #243 #248 and #249

**Comment by jayqi** [comment]
Looks like this is the fix: https://github.com/Rdatatable/data.table/issues/3938#issuecomment-538660958
