### ISSUE TITLE
CreatePackageReport() fails to list objects in package

### ISSUE THREAD

**Issue by jameslamb** [uptake/pkgnet#259]
Running this code

```r
CreatePackageReport(
    'kerdiest'
    , report_path = file.path(getwd(), 'whatever.html')
)
```

Yields the following error on the "Function Network" tab

```
## Error in as.environment(pos): no item called "package:kerdiest" on the search list
```

discovered via the code in #252

**Comment by TylerGrantSmith** [comment]
I was unable to reproduce this error, and it looks like everything worked as expected for me.
