### ISSUE TITLE
Example of calculating Jacard similarity does not work

### ISSUE THREAD

**Issue by marcpaterno** [uptake/pkgnet#271]
I am trying to follow the online example for calculation of Jacard similarity between function nodes. However, the code in this section of the online example seems not to be working. Here is a brief example:

```
library(pkgnet)
report <- CreatePackageReport(pkg_name="data.table")
# output omitted
> funcGraph <- report$FunctionReporter$pkg_graph
> funcNames <- igraph::vertex_attr(funcGraph, name = "name")
Error in igraph::vertex_attr(funcGraph, name = "name") : 
  Not a graph object
> sim <- igraph::similarity(graph = funcGraph, mode = "out", method = "jaccard")
Error in similarity.jaccard(graph, vids, mode, loops) : 
  Not a graph object
```

**Comment by bburns632** [comment]
@marcpaterno, thanks for pointing this out.  Could you confirm the version of pkgnet you are using?

**Comment by bburns632** [comment]
I suspect this has something to do with igraph's latest release: https://github.com/igraph/igraph/releases.  Looking into it.

**Comment by bburns632** [comment]
Here's the root of the issue which has probably existed for some time (13 months ish).  This Jaccard example is not the typical usage, so it went unnoticed (thanks again for the note @marcpaterno). 

Following the example above, `funcGraph` appears in the console as an igraph object
![image](https://user-images.githubusercontent.com/24531403/77837348-cde49c80-712d-11ea-81df-3957f1ff5ad9.png)

However, a closer looks at the object classes reveals that `igraph` class has been lost along the way. 
![image](https://user-images.githubusercontent.com/24531403/77837377-3cc1f580-712e-11ea-83d8-29ab9f6183ef.png)

**Comment by marcpaterno** [comment]
> @marcpaterno, thanks for pointing this out. Could you confirm the version of pkgnet you are using?

I have tried this using both version 0.4.0 from CRAN, and with 0.4.0.999 from GitHub.

**Comment by marcpaterno** [comment]
I may have inadvertently closed the issue when responding to your query regarding which version of pkgnet I was using.

**Comment by bburns632** [comment]
Ah, with the changes made about a year ago, the igraph format needs to be specified.  This will work.  That example will be updated in the next release. 

```
library(pkgnet)
report <- CreatePackageReport(pkg_name="data.table")
funcGraph <- report$FunctionReporter$pkg_graph$igraph
funcNames <- igraph::vertex_attr(funcGraph, name = "name")
sim <- igraph::similarity(graph = funcGraph, mode = "out", method = "jaccard")
```
