### ISSUE TITLE
Master failing for LaTex error

### ISSUE THREAD

**Issue by bburns632** [uptake/pkgnet#275]
![image](https://user-images.githubusercontent.com/24531403/78616332-8b137a80-7839-11ea-9a63-0291006bfa6d.png)

Linux is fine.  Apple fails. 

https://travis-ci.org/github/uptake/pkgnet/jobs/671850143?utm_medium=notification&utm_source=github_status

**Comment by bburns632** [comment]
@jameslamb @jayqi any ideas for this one?

**Comment by jameslamb** [comment]
This is a global TeX problem today 😬 

https://github.com/microsoft/LightGBM/pull/2976#issuecomment-609897646

**Comment by jayqi** [comment]
@jameslamb That does not look like the same problem.

From Googling, it is potentially an environment/dependency issue with Travis, where the macOS image's LaTeX is not the typical installation.

https://stackoverflow.com/a/55971429

It may fix itself over time, but we can also either try different Travis images or install the missing thing manually in the CI script.

**Comment by jameslamb** [comment]
We've been dealing with it most of today on LightGBM. I think it is the root of the issue. I think the package manager for TeX is failing to go get `inconsolata` because of it.

**Comment by jameslamb** [comment]
I think we can close this, it seems to have fixed itself. Here's a recent passed build oon `master`: https://travis-ci.org/github/uptake/pkgnet/builds/692805511
