### ISSUE TITLE
change main branch name

### ISSUE THREAD

**Issue by jameslamb** [uptake/pkgnet#282]
Earlier this year, many open source projects started changing the name of their main branch in git to something other than 'master', in an effort to be more inclusive. This project has avoided doing that so far because we use GitHub Pages to host https://uptake.github.io/pkgnet/.

GitHub [now allows you to host a GH Pages site from any branch](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages)

> You can publish your site from any branch in the repository, either from the root of the repository on that branch, `/`, or from the `/docs` folder on that branch

![image](https://user-images.githubusercontent.com/7608904/96391955-1aea9780-1180-11eb-88fb-bc5b0ce567ff.png)

Now that we have no technical things stopping us, I think we should change this repo's default branch from `master` to `main`.

@uptake/pkgnet what do you think?

**Comment by jayqi** [comment]
Sounds good. I don't have a preference either way.

**Comment by bburns632** [comment]
James,

Thanks for bringing it up.  I support it. We did this with my work repos
awhile back.

We could also take this opportunity to give our CI tools some love.

- Brian

**Comment by jameslamb** [comment]
ok thanks! I'll do this tonight
