### ISSUE TITLE
Is it possible to exclude (filter) some functions from a Function Network graph?

### ISSUE THREAD

**Issue by armenic** [uptake/pkgnet#301]
Dear developers,

Thank you so much for such an amazing package! 

I was wondering whether it is possible to excluded (filter) some functions from a Function Network graph? Let's say I have a function called `exclude_me()` and I do not want it to appear in the Functions Network visualization.

I know that one can click on the node in the visualization to make it active and grey out others. I am looking for a way to completely remove the node and arrows emanating from it.

I tried looking into the "Function Interdependency Reporter" object and it does not seem to have a writable method/field that can filter the edges and then create the visualization.

Thanks so much for your help!

**Comment by bburns632** [comment]
We always welcome contributions, but there are no immediately plans for new features at the moment.  This doesn't reflect the quality of the idea; it reflects the present momentum of development on this package.  Consequently, closing this item. Can reopen in future if you would like to contribute.
