### ISSUE TITLE
Handle functions referenced by name as a string when using do.call()

### ISSUE THREAD

**Issue by bburns632** [uptake/pkgnet#302]
_(I'm reposting a great question I received via email)_

Does the pkgnet pick up function calls that use do.call()? It seems it doesn't. For example, within a function in a package I am working on, I have this call

nuis <- do.call(".estimate_nuisance",                       
                args = c(data = list(data),
                         .key.inputs,
                         .nuis.inputs))

In this case pkgnet doesn't pick up the dependence on the function .estimate_nuisance(). In this particular package, this happens to be one of the key dependences, and we need to use do.call in order to tailor a bunch of options based on context, which we put in .nuis.inputs.

Is there an argument I can provide to CreatePackageReport() that would allow picking up dependencies through do.call()? If not, would you consider adding this?

**Comment by jameslamb** [comment]
I think this could be a useful feature, but I personally am not committing to working on it.

For anyone reading this post... I'd be happy to review a pull request proposing such a change. @bburns632 could you encourage whoever emailed you directly to come talk to us here, if they're interested in contributing that feature?

**Comment by bburns632** [comment]
Of course.  This was posted as a general question / call to action for the
pkgnet community.  To that end, if anyone is interested in developing this
feature, please comment on this ticket then start a PR.

**Comment by bburns632** [comment]
OK. Looking into this feature.  Would like to bounce this idea off you @jayqi as I recall much of the current function network code originally written by you.  

**Why do this?** 
`do.call` is a fairly widely used function.  Here's a quick search on github: https://github.com/search?q=do.call&type=code.  Accommodating this will produce more correct function graphs for packages that rely on it (like the original requester's). 

**Why doesn't it work now?**
`do.call` is a base function.  Presently, our scope for nodes is limited to the target package namespace (e.g. `names(pkgnet)`).  Base functions that are used within functions are overlooked. 

**Plan of attack**
After brushing up on how we extract the function network (which ultimately a string search sorta thing), I think adding some code after this matching section to look for `do.call` specifically and do some special node additions to the edges & node list is the best place.  Keep it similarly regex based with base functions. 

https://github.com/uptake/pkgnet/blob/main/R/FunctionReporter.R#L361-L374

**Design Decisions:**
1. _How to reflect this in the graph?_  
Do we include a `do.call` node that links to its argument or just link the function directly to the argument?  For `do.call`, I could see either. 

2. _Do we want to check for other base functions as well?_ 
We would need to limit expansion to those base functions directly referenced.  We would still need special accommodation for `do.call`.  This opens us up to a whole bunch of edgecases as well.  

3. _Nested `do.call`: where there's a function in the list of arguments.  Accommodate  or not?_ 
Do not look recursively seems like a half measure, but that could get ugly.

**Comment by jayqi** [comment]
With the caveat that I remember only like 5% of what we're doing here, how it works, why it works a certain way:

- I don't think considering the target to be _through_ `do.call` is the correct semantic representation here. The target function is directly referenced in the body of the source function, but it's just an argument of `do.call` rather than being called directly. Having the target be linked through `do.call` would be as if the body of `do.call` itself contained the target function.  
    - As such, I don't think this is a case of "we exclude base functions but we should". I think this is a case of "`do.call` is a unique way of invoking a function that we currently miss". 
    - Additionally IMO, `do.call` itself is not that interesting and is just machinery for calling the target function being used. I don't think adding a node for `do.call` would add any value to the graph. 
- Is this actually a case of whether or not the function is specified as a string reference to a name? i.e., is there a difference between `do.call(my_func, args = ...)` vs. `do.call("my_func", args = ...)`? I'm wondering if the former currently works fine, and it's just the latter that doesn't work. If so, we basically just need to special case the latter, because IIRC we currently discard atomic strings, but `do.call` is special because it will look up the string reference.

**Comment by bburns632** [comment]
@jayqi, on your second point, here are some quick edits on `baseballstats`.  Looks like we currently support the case with a function argument to `do.call`.  It's the function text name case that is not supported. 

**Normal (main branch):** 
<img width="386" alt="Screenshot 2024-04-09 at 10 49 47 PM" src="https://github.com/uptake/pkgnet/assets/24531403/920b5c1d-b4b5-4be1-b85c-fb67fcf8b30f">
<img width="520" alt="at_bat directly called" src="https://github.com/uptake/pkgnet/assets/24531403/1ab99c34-ef3e-40ac-b316-d32ef4305b0d">

**With text as a param:**
<img width="478" alt="Screenshot 2024-04-09 at 10 48 14 PM" src="https://github.com/uptake/pkgnet/assets/24531403/a58f8487-e2c7-407a-b937-3f6f469a3135">
<img width="504" alt="docall calling at_bat" src="https://github.com/uptake/pkgnet/assets/24531403/4c8dd1ad-7f0b-4f39-93db-b771dc872913">

**With function as a param:**
<img width="310" alt="image" src="https://github.com/uptake/pkgnet/assets/24531403/a57f05f6-2a7f-409d-bb52-1ce3503fdc6b">
<img width="542" alt="image" src="https://github.com/uptake/pkgnet/assets/24531403/fee04add-8a80-467f-8c80-b45d6d178c68">

Between each, I am quitting R without memory and recreating with this code chunk: 
```
library(devtools)
remove.packages("pkgnet")
devtools::install_local(".", force = TRUE, upgrade = "never")
devtools::install_local("inst/baseballstats", force = TRUE,upgrade = "never")
library(pkgnet)
t <- CreatePackageReport("baseballstats")
```

**Comment by bburns632** [comment]
Working on the edge case handling now
