### ISSUE TITLE
NOTE on Missing Tidy package causing Ubuntu jobs to fail

### ISSUE THREAD

**Issue by bburns632** [uptake/pkgnet#305]
I requested a fix in rhub here (https://github.com/r-hub/rhub-linux-builders/pull/71).  

Looking at putting in a short term work around for now via https://github.com/r-hub/rhub/issues/548

**Comment by jameslamb** [comment]
Thanks @bburns632 !

I *think* `r-hub/rhub-linux-builders` may be abandoned. Haven't seen that officially anywhere, but it seems like this repo has the same design goals and the same people are working on it: https://github.com/r-hub/containers

While `r-hub/rhub-linux-builders` hasn't had a new commit in 6+ months.

And looks like the ubuntu images from there come with `tidy` 😁 

https://github.com/r-hub/containers/blob/a559d410624ccd2b0cfabf597517a4f48e352ba9/containers/ubuntu-clang/Dockerfile#L100

**Comment by bburns632** [comment]
@jameslamb , saw that staleness but figured one liner was worth it to confirm.  R-hub's response confirmed those images are deprecated.  

A small two line patch to our github actions workflow patches our issue but now I'm curious on where the `ubuntu-latest` image (that we use) is coming from.  Note that `ubuntu-latest` is not on the list of supported images: https://r-hub.github.io/containers/.  

Should we switch to `ubuntu-next`?

**Comment by jameslamb** [comment]
The only uses I see in this repo of `"ubuntu-latest"` refer to GitHub Actions *virtual machine images*, not container images.

https://github.com/uptake/pkgnet/blob/9354e79795beb8ed07e22805707bc0c10107d458/.github/workflows/ci.yml#L20

https://github.com/uptake/pkgnet/blob/9354e79795beb8ed07e22805707bc0c10107d458/.github/workflows/smoke-tests.yaml#L15

Those are defined here: https://github.com/actions/runner-images

There is no `ubuntu-next` there.

**Comment by jameslamb** [comment]
So right now, here in `pkgnet` we aren't actually using *container* images at all.

We're asking GItHub Actions for an Ubuntu VM, and then setting up R with these GitHub Actions (Javascript code that downloads and installs R):

https://github.com/uptake/pkgnet/blob/9354e79795beb8ed07e22805707bc0c10107d458/.github/workflows/ci.yml#L29-L34

It'd probably be a good idea to update to later versions of those if they exist. You can check at https://github.com/r-lib/actions

**Comment by bburns632** [comment]
Alternatively, couldn't we leverage r-hub's Ubuntu R images that have these steps already built into the image? 

https://r-hub.github.io/containers/gha.html#for-your-own-package

**Comment by jameslamb** [comment]
Yeah totally! Switching to those container images would be better.

That'd make it easier to replicate CI locally, and it'd protect us from conflicts caused by the HUGE amount of stuff that GitHub pre-installs in its VM images (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md).

I totally support that change. We did that a while ago over in LightGBM and it's been great: https://github.com/microsoft/LightGBM/pull/5638

**Comment by bburns632** [comment]
@jameslamb which container from rhub would we use to replicate the MacOS compatibility testing we do now?  That's unclear to me.

**Comment by jameslamb** [comment]
You couldn't use container images for that. macOS would have to continue to run on a `macos-latest` virtual machine from GitHub Actions.
